### ISSUE TITLE
[BUG] - Grön bar sticker ut

### ISSUE THREAD

**Issue by theo8theo8** [Qognica/Qapsel#4]
**Describe the bug**
När man köpt väldigt få aktier så sticker den gröna baren ut

**To Reproduce**
1. Välj så många aktier det går av någon aktie
2. Välj en till aktie som du då har typ en av

**Expected behavior**
Mer rund kortare bättre

**Screenshots**
![Screenshot_2022-05-16-16-58-58-01_dd29807644f644134b550a21b1e8c262.jpg](https://user-images.githubusercontent.com/42777637/168623634-84323c98-9209-4a32-84c6-76496444df53.jpg)

**Device**
 - Device: [Realme GT Master Edition]
 - OS: [Android 11]
 - Version [15]

**Comment by SimonDamberg** [comment]
Tack för rapporten! Buggen är nu löst :)
