### ISSUE TITLE
[BUG] - Liten bar i annan färg

### ISSUE THREAD

**Issue by theo8theo8** [Qognica/Qapsel#5]
**Describe the bug**
Ovanför nästa-knappen för en marknad så finns det en smal liten bar med hörn rundade nedåt. Vet inte om ni ska ha dem där. Isåfall borde rundningen av hörnen bort. Annars bort helt.

**To Reproduce**
1. Gå in på valfri marknad
2. Skrolla längst ner

**Screenshots**
![Screenshot_2022-05-16-17-42-27-12_dd29807644f644134b550a21b1e8c262.jpg](https://user-images.githubusercontent.com/42777637/168632119-83e90786-8d7f-4ef3-b7ec-92aa55d1c5d9.jpg)

**Device**
 - Device: [Realme GT Master Edition]
 - OS: [Android 11]
 - Version [18]

**Comment by SimonDamberg** [comment]
Tack för rapporten! Buggen är nu löst :)
