### ISSUE TITLE
[BUG] - Översiktgrafen uppdateras ej

### ISSUE THREAD

**Issue by theo8theo8** [Qognica/Qapsel#6]
**Describe the bug**
Jag har haft aktier på detta konto från den 14/5-17/5, graferna per portfölj ser rätt ut. Men i Översiktgrafen finns bara 14/5-15/5

**To Reproduce**
Använd appen över flera dagar(kanske är helgen som är problem)

**Screenshots**
![Screenshot_2022-05-17-22-34-21-27_dd29807644f644134b550a21b1e8c262.jpg](https://user-images.githubusercontent.com/42777637/168905659-e53cb29f-3ad2-4520-9ac0-5d2815e88877.jpg)

**Device**
 - Device: [Realme GT Master Edition]
 - OS: [Android 11]
 - Version [0.4(20)]

**Comment by SimonDamberg** [comment]
Detta har fixats sedan offentliga 0.4 releasen tidigare idag. Rensa din handelshistorik från tidigare testning så kommer det lösa sig :)
